### ISSUE TITLE
 no module named 'core'

### ISSUE THREAD

**Issue by Cemm23333** [mhamilton723/STEGO#11]
Hello,Hi, thanks for sharing your code! I met with a question when I ran eval_segmention.py.How to deal with it?Thank you!

![image](https://user-images.githubusercontent.com/74448944/166862742-2bd774c3-8dbe-4887-85a4-a981b0829bab.png)

**Comment by JXFOnestep** [comment]
Me too! Have you fix it?

**Comment by MY-LIU100101** [comment]
In the previous code. The src/utils.py was called src/core.py. I think that is the origin of the problem. 

I avoid this error by changing the "run_picie" from True to False in the src/configs/eval_config.yml. (The picie is another unsupervised segmentation method compared in this work)

**Comment by mhamilton723** [comment]
@MY-LIU100101 thanks for finding the fix for this issue, I will double check on my side to see whether this is still happening on master

**Comment by Supgb** [comment]
The inappropriate model-saving approach might cause this issue. https://github.com/pytorch/pytorch/issues/18325#issuecomment-661759359
Saving only the state dict instead of the whole model object is more recommended. 
https://pytorch.org/docs/master/notes/serialization.html#recommended-approach-for-saving-a-model
